
#Disables certain types. Note that all these configs, like in any other mod, only hide stuff from tabs and disable their recipes
[types]

	[types.wood_type]

		[types.wood_type.mynethersdelight]
			powdery = true

		[types.wood_type.excessive_building]
			ancient = true
			willow = false
			maple = false

		[types.wood_type.cataclysm]
			chorus = true

		[types.wood_type.autumnity]
			maple = true

		[types.wood_type.caverns_and_chasms]
			azalea = true

		[types.wood_type.tconstruct]
			greenheart = false
			skyroot = false
			bloodshroom = false
			enderbark = false

		[types.wood_type.alexscaves]
			pewen = true
			thornwood = true

		[types.wood_type.wetland_whimsy]
			bald_cypress = true

		[types.wood_type.architects_palette]
			twisted = true

		[types.wood_type.botania]
			livingwood = true
			dreamwood = true

		[types.wood_type.quark]
			azalea = false
			ancient = false
			blossom = false

		[types.wood_type.ecologics]
			flowering_azalea = false
			azalea = false
			coconut = true
			walnut = true

		[types.wood_type.regions_unexplored]
			alpha = true
			baobab = true
			blackwood = true
			blue_bioshroom = true
			brimwood = true
			cobalt = true
			cypress = true
			dead = true
			eucalyptus = true
			green_bioshroom = true
			joshua = true
			kapok = true
			larch = true
			magnolia = true
			maple = true
			mauve = true
			palm = true
			pine = false
			pink_bioshroom = true
			redwood = true
			socotra = true
			willow = true
			yellow_bioshroom = true

		[types.wood_type.netherexp]
			claret = true

		[types.wood_type.upgrade_aquatic]
			driftwood = true
			river = true

		[types.wood_type.atmospheric]
			grimwood = true
			rosewood = true
			morado = true
			yucca = true
			aspen = true
			laurel = true
			kousa = true

		[types.wood_type.hexalia]
			cottonwood = true
			willow = true

		[types.wood_type.palegardenbackport]
			pale_oak = true

		[types.wood_type.aether]
			skyroot = true

		[types.wood_type.deep_aether]
			roseroot = true
			yagroot = true
			cruderoot = true
			conberry = true
			sunroot = true

		[types.wood_type.aether_redux]
			fieldsproot = true
			blightwillow = true
			cloudcap = true
			jellyshroom = true
			crystal = true
			glacia = true

	[types.leaves_type]

		[types.leaves_type.autumnity]
			yellow_maple = true
			orange_maple = true
			red_maple = true
			maple = true

		[types.leaves_type.alexscaves]
			ancient = true

		[types.leaves_type.excessive_building]
			golden_birch = true
			willow = true
			red_maple = true
			orange_maple = true
			yellow_maple = true
			ancient = true

		[types.leaves_type.culturaldelights]
			avocado = true
			fruiting_avocado = true

		[types.leaves_type.tconstruct]
			earth_slime = true
			sky_slime = true
			ender_slime = true

		[types.leaves_type.wetland_whimsy]
			bald_cypress = true

		[types.leaves_type.architects_palette]
			twisted = true

		[types.leaves_type.quark]
			ancient = true
			blue_blossom = true
			lavender_blossom = true
			orange_blossom = true
			yellow_blossom = true
			red_blossom = true

		[types.leaves_type.ecologics]
			coconut = true
			walnut = true

		[types.leaves_type.regions_unexplored]
			bamboo = true
			golden_larch = true
			alpha = true
			apple_oak = true
			baobab = true
			blackwood = true
			magnolia = true
			cypress = true
			dead = true
			dead_pine = true
			eucalyptus = true
			flowering = true
			kapok = true
			larch = true
			maple = true
			mauve = true
			orange_maple = true
			palm = true
			pine = true
			blue_magnolia = true
			pink_magnolia = true
			redwood = true
			red_maple = true
			brimwood = true
			enchanted_birch = true
			small_oak = true
			silver_birch = true
			socotra = true
			white_magnolia = true
			willow = true
			ashen = true

		[types.leaves_type.hexalia]
			cottonwood = true
			willow = true

		[types.leaves_type.palegardenbackport]
			pale_oak = true

		[types.leaves_type.upgrade_aquatic]
			river = true

		[types.leaves_type.atmospheric]
			rosewood = true
			morado = true
			flowering_morado = true
			yucca = true
			aspen = true
			green_aspen = true
			laurel = true
			dry_laurel = true
			kousa = true
			currant = true
			grimwood = true

		[types.leaves_type.aether]
			golden_oak = true
			holiday = true
			decorated_holiday = true
			crystal = true
			crystal_fruit = true
			skyroot = true

		[types.leaves_type.deep_aether]
			flowering_roseroot = true
			blue_roseroot = true
			flowering_blue_roseroot = true
			roseroot = true
			yagroot = true
			cruderoot = true
			conberry = true
			sunroot = true

		[types.leaves_type.aether_redux]
			fieldsproot = true
			gilded_oak = true
			blighted_skyroot = true
			purple_glacia = true
			blightwillow = true
			glacia = true

#Disables specific entries
[entries]

	[entries.wood_type]

		[entries.wood_type.excessive_building]
			chiseled = true
			vertical_stairs = false
			mosaic_slab = true
			crafting_table = true
			ladder = true
			bookshelf = true
			decorative_shelf = true
			mosaic_vertical_stairs = false
			mosaic = true
			hollow_log = false
			mosaic_stairs = true
			hollow_stripped_log = false

		[entries.wood_type.farmersdelight]
			cabinet = true

		[entries.wood_type.architects_palette]
			board_stairs = true
			railing = true
			board_slab = true
			boards = true
			board_wall = true

		[entries.wood_type.quark]
			hollow_log = false
			vertical_planks = true
			post = false
			trapped_chest = true
			bookshelf = false
			chest = false
			stripped_post = false
			ladder = false
			vertical_slab = true

		[entries.wood_type.regions_unexplored]
			branch = true

		[entries.wood_type.friendsandfoes]
			beehive = true

		[entries.wood_type.storagedrawers]
			trim = true
			full_drawers_2 = true
			half_drawers_1 = true
			full_drawers_4 = true
			half_drawers_4 = true
			half_drawers_2 = true
			full_drawers_1 = true

	[entries.leaves_type]

		[entries.leaves_type.quark]
			hedge = true
			leaf_carpet = true

		[entries.leaves_type.regions_unexplored]
			shrub = true

