
[logbegone]
	phrases = ["Disconnecting VANILLA connection attempt", "Channels ", "Couldn't parse element", "EMI", "TMRV"]
	regex = ["Disconnecting VANILLA connection attempt", "Channels ", "EMI", "TMRV", "Couldn't parse element"]

