
["Minigame Config"]
	#Default arrow speed for the forging minigame
	#Range: -5.0 ~ 5.0
	arrowSpeed = 2.0
	#Toggle for the forging minigame. You cannot craft with unpolished tool heads and the quality modifier is disabled if set to false.
	enableMinigame = true
	#Default arrow speed increase for the forging minigame
	#Range: -5.0 ~ 5.0
	arrowSpeedIncrease = 0.8
	#How likely it is for the player to get Masterfully Forged. Set to 0 to disable it.
	#Range: 0.0 ~ 1.0
	masterQualityChance = 0.05
	#Maximum arrow speed for the forging minigame
	#Range: -10.0 ~ 10.0
	maxArrowSpeed = 5.0
	#Zone starting size for the forging minigame,  in chance
	#Range: 0 ~ 100
	zoneStartingSize = 20
	#Zone shrink factor for the forging minigame, default value here means that it shrinks to 70% of its original size
	#Range: 0.0 ~ 1.0
	zoneShrinkFactor = 0.7
	#Maximum distance you can go from your Smithing Anvil before minigame reset
	#Range: 0 ~ 1000
	maxAnvilDistance = 100
	#Smallest perfect zone it can become
	#Range: 0 ~ 100
	minPerfectZone = 3
	#Minigame resets after a certain amount of ticks
	#Range: 0 ~ 36000
	minigameTimeout = 6000

["Balance Options"]
	#Defines the base durability multiplier of all items that has durability.
	#Range: 0.0 ~ 10000.0
	durability = 1.0

["Weapon Damage Bonuses"]
	#Damage bonus for master quality weapons
	#Range: -10.0 ~ 10.0
	masterWeaponDamage = 3.0
	#Damage bonus for perfect quality weapons
	#Range: -10.0 ~ 10.0
	perfectWeaponDamage = 2.0
	#Damage bonus for expert quality weapons
	#Range: -10.0 ~ 10.0
	expertWeaponDamage = 1.5
	#Damage bonus for well-made quality weapons
	#Range: -10.0 ~ 10.0
	wellWeaponDamage = 0.0
	#Damage penalty for poor quality weapons
	#Range: -10.0 ~ 10.0
	poorWeaponDamage = -1.0

["Weapon Speed Bonuses"]
	#Attack speed bonus for master quality weapons
	#Range: -2.0 ~ 2.0
	masterWeaponSpeed = 1.0
	#Attack speed bonus for perfect quality weapons
	#Range: -2.0 ~ 2.0
	perfectWeaponSpeed = 0.5
	#Attack speed bonus for expert quality weapons
	#Range: -2.0 ~ 2.0
	expertWeaponSpeed = 0.25
	#Attack speed bonus for well-made quality weapons
	#Range: -2.0 ~ 2.0
	wellWeaponSpeed = 0.0
	#Attack speed penalty for poor quality weapons
	#Range: -2.0 ~ 2.0
	poorWeaponSpeed = -0.5

["Armor Bonuses"]
	#Armor bonus for master quality armor
	#Range: -5.0 ~ 5.0
	masterArmorBonus = 2.0
	#Armor bonus for perfect quality armor
	#Range: -5.0 ~ 5.0
	perfectArmorBonus = 1.5
	#Armor bonus for expert quality armor
	#Range: -5.0 ~ 5.0
	expertArmorBonus = 1.0
	#Armor bonus for well-made quality armor
	#Range: -5.0 ~ 5.0
	wellArmorBonus = 0.0
	#Armor penalty for poor quality armor
	#Range: -5.0 ~ 5.0
	poorArmorBonus = -1.0

["Knapping Config"]
	#How likely it is for rock to drop from flint carving stone
	#Range: 0.0 ~ 1.0
	rockDroppingChance = 0.1
	#How likely it is for flint to break when carving stone
	#Range: 0.0 ~ 1.0
	flintBreakingChance = 0.1

["Grinding Config"]
	#How much the item durability reduce per grindstone use
	#Range: 0.0 ~ 1.0
	durabilityReduce = 0.05
	#How much the item's durability restore per grindstone use. Should be larger than durability reduce per grind to avoid durability going to the negative
	#Range: 0.0 ~ 1.0
	damageRestore = 0.1

